query($cursor: String, $commentCount: Int, $commentCursor: String) {
  todos(limit: 5, cursor: $cursor) {
    cursor
    posts {
      id
      content
      user {
        username
        id
        profilepic
      }
      likes {
        total
        isLiked
      }
      comments(limit: $commentCount, cursor: $commentCursor) {
        total
        cursor
        hasMore
        comments {
          comment
          user {
            id
            profilepic
            username
          }
        }
      }
      createdAt
      images
    }
  }
}
